# Generated by Django 6.0.7 on 2026-07-18 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools_registry', '0002_tool_faq_tool_howto_steps_tool_related_slugs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('template_text', models.TextField()),
                ('purpose', models.CharField(choices=[('tool_description', 'Tool description'), ('seo_title', 'SEO title'), ('meta', 'Meta description'), ('faq', 'FAQ'), ('blog', 'Blog'), ('tutorial', 'Tutorial'), ('comparison', 'Comparison'), ('landing', 'Landing')], db_index=True, max_length=32)),
                ('locale', models.CharField(db_index=True, default='en', max_length=10)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(db_index=True, default='blog', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_generated', 'AI generated'), ('human_review', 'Human review'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('locale', models.CharField(db_index=True, default='en', max_length=10)),
                ('target_path', models.CharField(blank=True, default='', max_length=512)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('prompt', models.TextField(blank=True, default='')),
                ('response_excerpt', models.TextField(blank=True, default='')),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('queued', 'Queued')], db_index=True, default='queued', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='content_factory.contentitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True, default='')),
                ('meta_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content_factory.contentitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'locale'], name='content_fac_status_f979f7_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type', 'status'], name='content_fac_content_e1c460_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentversion',
            unique_together={('content', 'revision')},
        ),
    ]
