# Generated by Django 6.0.7 on 2026-07-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0001_growth_engine'),
        ('keywords', '0001_global_launch_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopilotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(blank=True, db_index=True, default='pending', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('human_review', 'Human review'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('quality_score', models.FloatField(default=0.0)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='content_factory.contentitem')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='keywords.keywordopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
