# Generated by Django 6.0.7 on 2026-07-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth_agent', '0001_launch_scale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='growthinsight',
            new_name='growth_agen_status_fa90fc_idx',
            old_name='growth_agen_status_prio_idx',
        ),
        migrations.RenameIndex(
            model_name='growthinsight',
            new_name='growth_agen_categor_f4d74f_idx',
            old_name='growth_agen_cat_status_idx',
        ),
    ]
