# Generated by Django 6.0.7 on 2026-07-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_agent', '0002_launch_scale_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('priority', models.IntegerField(db_index=True, default=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('done', 'Done'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='growth_agent.growthinsight')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', '-priority'], name='growth_agen_status_7bf7b5_idx'), models.Index(fields=['category', 'status'], name='growth_agen_categor_373b40_idx')],
            },
        ),
    ]
