"""Marketplace billing + SDK helpers."""

from __future__ import annotations

from calendar import monthrange
from datetime import date
from pathlib import Path
from typing import Any

from django.conf import settings
from django.db.models import Sum
from django.utils import timezone

from apps.marketplace.models import ApiInvoiceStub, ApiKey, ApiUsage, DeveloperOrganization

SDK_STUB = '''/**
 * ToolVerse AI API Client (stub)
 * Generated by `manage.py generate_sdk`
 */

export type ApiClientOptions = {
  baseUrl?: string;
  apiKey: string;
};

export class ToolVerseApiClient {
  readonly baseUrl: string;
  readonly apiKey: string;

  constructor(options: ApiClientOptions) {
    this.baseUrl = (options.baseUrl || "https://api.toolverse.ai/api/v1").replace(/\\/$/, "");
    this.apiKey = options.apiKey;
  }

  async request<T = unknown>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers || {});
    headers.set("Authorization", `Bearer ${this.apiKey}`);
    headers.set("Accept", "application/json");
    if (init.body && !headers.has("Content-Type")) {
      headers.set("Content-Type", "application/json");
    }
    const res = await fetch(`${this.baseUrl}${path.startsWith("/") ? path : `/${path}`}`, {
      ...init,
      headers,
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`ToolVerse API ${res.status}: ${text}`);
    }
    return (await res.json()) as T;
  }

  listTools(params?: { compact?: boolean }) {
    const q = params?.compact ? "?compact=1" : "";
    return this.request(`/mobile/tools/${q}`);
  }
}

export default ToolVerseApiClient;
'''

PACKAGE_JSON = """{
  "name": "@toolverse/api-client",
  "version": "0.1.0",
  "private": true,
  "main": "src/index.ts",
  "types": "src/index.ts",
  "description": "Stub TypeScript client for ToolVerse AI public API"
}
"""


def _monorepo_packages_dir() -> Path:
    """Resolve MegaTools AI/packages from apps/api BASE_DIR."""
    api_root = Path(settings.BASE_DIR).resolve()
    # BASE_DIR = .../MegaTools AI/apps/api → packages = .../MegaTools AI/packages
    return api_root.parent.parent / "packages"


def generate_sdk(*, root: Path | None = None) -> dict[str, Any]:
    """Write packages/api-client stub TypeScript package."""
    base = root or (_monorepo_packages_dir() / "api-client")
    src = base / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "index.ts").write_text(SDK_STUB, encoding="utf-8")
    (base / "package.json").write_text(PACKAGE_JSON, encoding="utf-8")
    return {"path": str(base), "files": ["package.json", "src/index.ts"]}


def generate_invoices_from_usage(*, as_of: date | None = None) -> dict[str, Any]:
    """
    Create ApiInvoiceStub drafts from ApiUsage for each DeveloperOrganization.
    """
    as_of = as_of or timezone.now().date()
    period_start = date(as_of.year, as_of.month, 1)
    last_day = monthrange(as_of.year, as_of.month)[1]
    period_end = date(as_of.year, as_of.month, last_day)

    created = 0
    for org in DeveloperOrganization.objects.select_related("owner").all():
        usage_qs = ApiUsage.objects.filter(
            api_key__user=org.owner,
            created_at__date__gte=period_start,
            created_at__date__lte=period_end,
        )
        units = int(usage_qs.aggregate(total=Sum("units")).get("total") or 0)
        if units <= 0:
            units = int(
                ApiKey.objects.filter(user=org.owner, revoked_at__isnull=True)
                .aggregate(total=Sum("usage_this_month"))
                .get("total")
                or 0
            )
        if units <= 0:
            continue
        amount_cents = max(1, units)
        stub, was_created = ApiInvoiceStub.objects.update_or_create(
            org=org,
            period_start=period_start,
            period_end=period_end,
            defaults={
                "amount_cents": amount_cents,
                "usage_units": units,
                "status": ApiInvoiceStub.Status.DRAFT,
            },
        )
        created += 1
    return {"created": created, "period_start": str(period_start), "period_end": str(period_end)}
