# Generated by Django 6.0.7 on 2026-07-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools_registry', '0003_traffic_revenue_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('banner', 'Banner'), ('in-tool', 'In tool'), ('sidebar', 'Sidebar'), ('satellite', 'Satellite')], db_index=True, max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('network', models.CharField(choices=[('adsense', 'AdSense'), ('custom', 'Custom')], default='adsense', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('destination_url', models.URLField(max_length=1024)),
                ('network', models.CharField(blank=True, default='', max_length=64)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ad_impression', 'Ad impression'), ('ad_click', 'Ad click'), ('subscription', 'Subscription'), ('affiliate', 'Affiliate'), ('api', 'API')], db_index=True, max_length=32)),
                ('amount_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', '-created_at'], name='monetizatio_type_1c21be_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsoredTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('creative', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_entries', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['-priority', '-updated_at'],
            },
        ),
    ]
