# Generated by Django 6.0.7 on 2026-07-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('premium', models.BooleanField(default=False)),
                ('adsense_slot', models.CharField(default='sidebar', max_length=32)),
                ('seo_title', models.JSONField(default=dict)),
                ('seo_description', models.JSONField(blank=True, default=dict)),
                ('seo_keywords', models.JSONField(default=list)),
                ('schema_type', models.CharField(default='WebApplication', max_length=64)),
                ('capabilities', models.JSONField(default=list)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveBigIntegerField(default=0)),
                ('search_document', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='tools_registry.category')),
            ],
            options={
                'ordering': ['order', 'slug'],
                'indexes': [models.Index(fields=['category', 'slug'], name='tools_regis_categor_ffa502_idx'), models.Index(fields=['premium', 'is_active'], name='tools_regis_premium_defa75_idx')],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
