# Generated by Django 6.0.7 on 2026-07-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='faq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='howto_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='related_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='source',
            field=models.CharField(choices=[('filesystem', 'Filesystem'), ('dynamic', 'Dynamic')], db_index=True, default='filesystem', max_length=20),
        ),
        migrations.CreateModel(
            name='DynamicToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('category_slug', models.SlugField(default='ai', max_length=64)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('premium', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.JSONField(blank=True, default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('howto_steps', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('adsense_slot', models.CharField(default='sidebar', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='definition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_tool', to='tools_registry.dynamictooldefinition'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['source', 'is_active'], name='tools_regis_source_7e9961_idx'),
        ),
    ]
