# Generated by Django 6.0.7 on 2026-07-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_registry', '0002_tool_faq_tool_howto_steps_tool_related_slugs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolGrowthMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_viral', models.BooleanField(db_index=True, default=False)),
                ('share_text', models.JSONField(blank=True, default=dict)),
                ('og_template', models.CharField(blank=True, default='', max_length=64)),
                ('share_platforms', models.JSONField(blank=True, default=list)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth_meta', to='tools_registry.tool')),
            ],
            options={
                'verbose_name': 'Tool growth meta',
                'verbose_name_plural': 'Tool growth meta',
            },
        ),
    ]
