# Generated by Django 6.0.7 on 2026-07-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('infra', 'Infra'), ('seo', 'SEO'), ('analytics', 'Analytics'), ('payments', 'Payments'), ('email', 'Email'), ('security', 'Security'), ('monitoring', 'Monitoring')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
