# Generated by Django 6.0.7 on 2026-07-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_global_launch_engine'),
        ('tool_factory', '0001_traffic_revenue_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('category_slug', models.SlugField(max_length=64)),
                ('recipe', models.CharField(default='generic', max_length=32)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.JSONField(blank=True, default=list)),
                ('priority_weight', models.FloatField(default=1.0)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ToolOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_slug', models.SlugField(max_length=128, unique=True)),
                ('category_slug', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True, default='')),
                ('seo_score', models.FloatField(default=0.0)),
                ('demand_score', models.FloatField(default=0.0)),
                ('competition_score', models.FloatField(default=0.0)),
                ('value_score', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('queued', 'Queued'), ('built', 'Built'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('keywords', models.ManyToManyField(blank=True, related_name='tool_opportunities', to='keywords.keywordopportunity')),
                ('tool_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='tool_factory.toolspec')),
            ],
            options={
                'verbose_name_plural': 'Tool opportunities',
                'ordering': ['-priority_score'],
            },
        ),
    ]
