# Generated by Django 6.0.7 on 2026-07-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_intelligence', '0001_global_launch_engine'),
        ('tools_registry', '0003_traffic_revenue_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traffic_score', models.FloatField(default=0.0)),
                ('usage_score', models.FloatField(default=0.0)),
                ('revenue_score', models.FloatField(default=0.0)),
                ('seo_score', models.FloatField(default=0.0)),
                ('retention_score', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_score', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
    ]
