# Generated by Django 6.0.7 on 2026-07-18 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('category_slug', models.SlugField(default='ai', max_length=64)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.JSONField(blank=True, default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('howto', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('recipe', models.CharField(choices=[('generic', 'Generic'), ('pdf', 'PDF'), ('image', 'Image'), ('ai', 'AI'), ('developer', 'Developer'), ('calculator', 'Calculator')], db_index=True, default='generic', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('is_viral', models.BooleanField(default=False)),
                ('share_text', models.JSONField(blank=True, default=dict)),
                ('export_filesystem', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_specs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolFactoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('log', models.JSONField(blank=True, default=list)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tool_factory.toolspec')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
