# Generated by Django 6.0.7 on 2026-07-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools_registry', '0003_traffic_revenue_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('type', models.CharField(choices=[('title', 'Title'), ('meta', 'Meta'), ('faq', 'FAQ'), ('internal_link', 'Internal link'), ('content', 'Content')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('suggestion', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_recommendations', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['path', 'status'], name='seo_optimiz_path_f6187e_idx'), models.Index(fields=['type', 'status'], name='seo_optimiz_type_24e1fc_idx')],
            },
        ),
    ]
