# Generated by Django 6.0.7 on 2026-07-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_optimizer', '0002_launch_scale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seohealthscore',
            new_name='seo_optimiz_overall_a0d286_idx',
            old_name='seo_optimiz_overall_idx',
        ),
        migrations.RenameIndex(
            model_name='seohealthscore',
            new_name='seo_optimiz_analyze_1d6323_idx',
            old_name='seo_optimiz_analyze_idx',
        ),
    ]
