# Generated by Django 6.0.7 on 2026-07-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_global_launch_engine'),
        ('seo_optimizer', '0003_launch_scale_fix'),
        ('tool_intelligence', '0001_global_launch_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoOpportunityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('keyword', 'Keyword'), ('gsc', 'GSC'), ('health', 'Health'), ('opportunity', 'Opportunity')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(db_index=True, default=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('suggested_action', models.CharField(choices=[('create_tool', 'Create tool'), ('write_content', 'Write content'), ('fix_seo', 'Fix SEO'), ('internal_links', 'Internal links')], default='write_content', max_length=32)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_opportunity_tasks', to='keywords.keywordopportunity')),
                ('tool_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_opportunity_tasks', to='tool_intelligence.toolopportunity')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', '-priority'], name='seo_optimiz_status_8cabd9_idx'), models.Index(fields=['source', 'status'], name='seo_optimiz_source_ee5bcf_idx')],
            },
        ),
    ]
