#!/usr/bin/env node
/**
 * Globs src/tools/<id>/index.ts and writes src/tools/tools.generated.ts
 * exporting a map of tools keyed by slug from each module's manifest.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const webRoot = path.resolve(__dirname, "..");
const toolsDir = path.join(webRoot, "src", "tools");
const outFile = path.join(toolsDir, "tools.generated.ts");

function listToolDirs() {
  if (!fs.existsSync(toolsDir)) return [];
  return fs
    .readdirSync(toolsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith("_") && !d.name.startsWith("."))
    .map((d) => d.name)
    .filter((name) => fs.existsSync(path.join(toolsDir, name, "index.ts")))
    .sort();
}

function toIdent(id) {
  return id.replace(/[^a-zA-Z0-9_$]/g, "_").replace(/^(\d)/, "_$1");
}

const dirs = listToolDirs();

const imports = dirs
  .map((id) => `import ${toIdent(id)} from "./${id}";`)
  .join("\n");

const entries = dirs
  .map((id) => {
    const ident = toIdent(id);
    return `  [${ident}.manifest.slug]: ${ident},`;
  })
  .join("\n");

const content = `/**
 * Auto-generated by scripts/generate-tools.mjs — do not edit by hand.
 * Run: npm run generate:tools
 */
import type { ToolFrontendModule } from "@toolverse/tool-sdk";
${imports ? `${imports}\n` : ""}
export const toolsBySlug: Record<string, ToolFrontendModule> = {
${entries}
};

export const toolSlugs = Object.keys(toolsBySlug) as string[];

export default toolsBySlug;
`;

fs.writeFileSync(outFile, content, "utf8");
console.log(
  `[generate-tools] Wrote ${path.relative(webRoot, outFile)} with ${dirs.length} tool(s): ${dirs.join(", ") || "(none)"}`,
);
