# Generated by Django 6.0.7 on 2026-07-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Unique path key, e.g. best/pdf-tools or json/json-formatter-online', max_length=255, unique=True)),
                ('path_pattern', models.CharField(blank=True, default='', help_text='Pattern template, e.g. best/{topic}, tools/for-{audience}', max_length=255)),
                ('title', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('page_type', models.CharField(choices=[('best_of', 'Best of'), ('keyword', 'Keyword'), ('audience', 'Audience'), ('category_hub', 'Category hub')], db_index=True, default='keyword', max_length=32)),
                ('topic', models.CharField(blank=True, default='', max_length=128)),
                ('category_slug', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('audience', models.CharField(blank=True, default='', max_length=128)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('related_tool_ids', models.JSONField(blank=True, default=list)),
                ('seo_title', models.JSONField(blank=True, default=dict)),
                ('seo_description', models.JSONField(blank=True, default=dict)),
                ('seo_keywords', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['status', 'page_type'], name='programmati_status_08493e_idx'), models.Index(fields=['category_slug', 'status'], name='programmati_categor_f00670_idx')],
            },
        ),
    ]
