# Generated by Django 6.0.7 on 2026-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_seo', '0001_growth_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmaticpage',
            name='page_type',
            field=models.CharField(choices=[('best_of', 'Best of'), ('keyword', 'Keyword'), ('audience', 'Audience'), ('category_hub', 'Category hub'), ('authority', 'Authority')], db_index=True, default='keyword', max_length=32),
        ),
    ]
