# Generated by Django 6.0.7 on 2026-07-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['name', '-created_at'], name='analytics_a_name_82eb48_idx'),
        ),
    ]
