# Generated by Django 6.0.7 on 2026-07-18 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tool_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('event_name', models.CharField(db_index=True, max_length=128)),
                ('count', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'ordering': ['-date', 'event_name'],
            },
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='referrer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='tool_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user_agent_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['tool_id', '-created_at'], name='analytics_a_tool_id_aa526d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['country', '-created_at'], name='analytics_a_country_f87ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailyrollup',
            index=models.Index(fields=['date', 'event_name'], name='analytics_a_date_443b16_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailyrollup',
            index=models.Index(fields=['date', 'tool_id'], name='analytics_a_date_a7b8a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsdailyrollup',
            unique_together={('date', 'tool_id', 'event_name', 'country')},
        ),
    ]
