from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from django.conf import settings
from django.db import transaction
from django.utils.text import slugify

from apps.tool_factory.models import ToolFactoryJob, ToolSpec
from apps.tools_registry.cache import invalidate_tool_caches
from apps.tools_registry.dynamic_models import DynamicToolDefinition
from apps.tools_registry.growth_models import ToolGrowthMeta
from apps.tools_registry.publish import publish_dynamic_tool

logger = logging.getLogger("toolverse.tool_factory")

GENERATED_TESTS_DIR = Path(__file__).resolve().parent / "generated_tests"

API_SCAFFOLD_MANIFEST = """{{
  "id": "{slug}",
  "slug": "{slug}",
  "category": "{category}",
  "name": {name_json},
  "description": {description_json},
  "version": "1.0.0",
  "premium": false,
  "adsenseSlot": "sidebar",
  "seo": {seo_json},
  "schemaType": "SoftwareApplication",
  "capabilities": {capabilities_json},
  "icon": "sparkles",
  "order": 99
}}
"""

API_SCAFFOLD_INIT = '''"""Filesystem scaffold generated by Tool Factory for {slug}."""

from tools.base import BaseToolPlugin


class {class_name}Plugin(BaseToolPlugin):
    tool_id = "{slug}"

    def get_urls(self):
        return []


plugin = {class_name}Plugin()
'''

WEB_MANIFEST_TS = """import type {{ ToolManifest }} from "@toolverse/tool-sdk";

export const manifest: ToolManifest = {{
  id: "{slug}",
  slug: "{slug}",
  category: "{category}" as ToolManifest["category"],
  name: {name_json},
  description: {description_json},
  version: "1.0.0",
  premium: false,
  adsenseSlot: "sidebar",
  capabilities: {capabilities_json},
  icon: "sparkles",
  order: 99,
  seo: {seo_json},
  schemaType: "SoftwareApplication",
}};
"""

WEB_INDEX_TS = """import type {{ ToolFrontendModule }} from "@toolverse/tool-sdk";
import {{ DynamicToolRuntime }} from "@/components/DynamicToolRuntime";
import {{ manifest }} from "./manifest";

const mod: ToolFrontendModule = {{
  manifest,
  Component: DynamicToolRuntime as unknown as ToolFrontendModule["Component"],
}};

export default mod;
export {{ manifest }};
"""

TEST_STUB = '''"""Generated smoke test for dynamic tool `{slug}`."""

import pytest
from rest_framework.test import APIClient


@pytest.mark.django_db
def test_{safe_slug}_endpoint_smoke():
    client = APIClient()
    response = client.post(
        "/api/v1/t/dynamic/{slug}/run/",
        {{"input": {{}}}},
        format="json",
    )
    # Stub: endpoint is reachable (may validate input and return 400)
    assert response.status_code in (200, 400, 404)
    assert True
'''


def _class_name(slug: str) -> str:
    parts = [p for p in slug.replace("-", "_").split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Generated"


def _append_log(job: ToolFactoryJob | None, message: str) -> None:
    if job is None:
        return
    log = list(job.log or [])
    log.append(message)
    job.log = log
    job.save(update_fields=["log"])


def _write_pytest_stub(slug: str) -> Path:
    GENERATED_TESTS_DIR.mkdir(parents=True, exist_ok=True)
    safe = slugify(slug).replace("-", "_") or "tool"
    path = GENERATED_TESTS_DIR / f"test_{safe}.py"
    path.write_text(TEST_STUB.format(slug=slug, safe_slug=safe), encoding="utf-8")
    init = GENERATED_TESTS_DIR / "__init__.py"
    if not init.exists():
        init.write_text("", encoding="utf-8")
    return path


def _export_filesystem(spec: ToolSpec) -> dict[str, str]:
    name_json = json.dumps(spec.name or {"en": spec.slug}, ensure_ascii=False)
    description_json = json.dumps(spec.description or {"en": ""}, ensure_ascii=False)
    seo = spec.seo if isinstance(spec.seo, dict) else {}
    if "title" not in seo:
        seo = {**seo, "title": spec.name or {"en": spec.slug}}
    if "description" not in seo:
        seo = {**seo, "description": spec.description or {"en": ""}}
    if "keywords" not in seo:
        seo = {**seo, "keywords": [spec.slug.replace("-", " ")]}
    seo_json = json.dumps(seo, ensure_ascii=False)
    caps = spec.capabilities or ["server"]
    capabilities_json = json.dumps(caps, ensure_ascii=False)
    class_name = _class_name(spec.slug)

    api_dir = Path(settings.BASE_DIR) / "tools" / spec.slug
    api_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = api_dir / "manifest.json"
    init_path = api_dir / "__init__.py"
    manifest_path.write_text(
        API_SCAFFOLD_MANIFEST.format(
            slug=spec.slug,
            category=spec.category_slug,
            name_json=name_json,
            description_json=description_json,
            seo_json=seo_json,
            capabilities_json=capabilities_json,
        ),
        encoding="utf-8",
    )
    init_path.write_text(
        API_SCAFFOLD_INIT.format(slug=spec.slug, class_name=class_name),
        encoding="utf-8",
    )

    web_root = Path(settings.BASE_DIR).parents[1] / "web" / "src" / "tools" / spec.slug
    # Prefer monorepo apps/web when BASE_DIR is apps/api
    alt_web = Path(settings.BASE_DIR).parent / "web" / "src" / "tools" / spec.slug
    web_dir = alt_web if alt_web.parent.parent.parent.exists() else web_root
    web_dir.mkdir(parents=True, exist_ok=True)
    web_manifest = web_dir / "manifest.ts"
    web_index = web_dir / "index.ts"
    web_manifest.write_text(
        WEB_MANIFEST_TS.format(
            slug=spec.slug,
            category=spec.category_slug,
            name_json=name_json,
            description_json=description_json,
            seo_json=seo_json,
            capabilities_json=capabilities_json,
        ),
        encoding="utf-8",
    )
    web_index.write_text(WEB_INDEX_TS, encoding="utf-8")

    return {
        "api_manifest": str(manifest_path),
        "api_init": str(init_path),
        "web_manifest": str(web_manifest),
        "web_index": str(web_index),
    }


def _maybe_create_howto_content(spec: ToolSpec, tool, user=None) -> int | None:
    try:
        from apps.content_factory.models import ContentItem
    except Exception:  # noqa: BLE001
        return None

    try:
        title = f"How to use {(spec.name or {}).get('en') or spec.slug}"
        body_parts: list[str] = [f"# {title}", ""]
        howto = spec.howto if isinstance(spec.howto, list) else []
        for i, step in enumerate(howto, start=1):
            if isinstance(step, dict):
                text = step.get("en") or step.get("text") or str(step)
            else:
                text = str(step)
            body_parts.append(f"{i}. {text}")
        body = "\n".join(body_parts) if howto else f"# {title}\n\nOpen the tool and follow the on-screen steps."
        slug = f"howto-{spec.slug}"[:240]
        content, _ = ContentItem.objects.update_or_create(
            slug=slug,
            defaults={
                "title": title[:255],
                "body": body,
                "content_type": "howto",
                "status": ContentItem.Status.DRAFT,
                "locale": "en",
                "tool": tool,
                "target_path": f"/tools/{spec.category_slug}/{spec.slug}",
                "meta_title": title[:255],
                "meta_description": (spec.description or {}).get("en", "")[:2000],
                "created_by": user if getattr(user, "is_authenticated", False) else None,
            },
        )
        return content.pk
    except Exception as exc:  # noqa: BLE001
        logger.warning("howto ContentItem skipped: %s", exc)
        return None


@transaction.atomic
def build_tool_from_spec(spec_id: int, user=None) -> dict[str, Any]:
    """
    Build a live dynamic Tool from a ToolSpec.
    Returns artifact metadata including tool_id and paths.
    """
    spec = ToolSpec.objects.select_for_update().get(pk=spec_id)
    job = ToolFactoryJob.objects.create(
        spec=spec,
        status=ToolFactoryJob.Status.RUNNING,
        log=["build started"],
        artifacts={},
    )

    try:
        spec.status = ToolSpec.Status.GENERATING
        spec.error = ""
        spec.save(update_fields=["status", "error", "updated_at"])
        _append_log(job, "status=generating")

        definition, _ = DynamicToolDefinition.objects.update_or_create(
            slug=spec.slug,
            defaults={
                "category_slug": spec.category_slug,
                "name": spec.name or {"en": spec.slug},
                "description": spec.description or {"en": ""},
                "ui_schema": spec.ui_schema or {},
                "pipeline": spec.pipeline or [],
                "seo": spec.seo or {},
                "faq": spec.faq or [],
                "howto_steps": spec.howto or [],
                "capabilities": spec.capabilities or ["server"],
                "status": DynamicToolDefinition.Status.PUBLISHED,
                "created_by": user
                if getattr(user, "is_authenticated", False)
                else spec.created_by,
            },
        )
        _append_log(job, f"dynamic definition upserted id={definition.pk}")

        tool = publish_dynamic_tool(definition)
        _append_log(job, f"published tool_id={tool.tool_id}")

        tool.faq = spec.faq or []
        tool.howto_steps = spec.howto or []
        seo = spec.seo if isinstance(spec.seo, dict) else {}
        if seo.get("title"):
            tool.seo_title = seo["title"]
        if seo.get("description"):
            tool.seo_description = seo["description"]
        if seo.get("keywords"):
            tool.seo_keywords = seo["keywords"]
        if spec.is_viral:
            tool.related_slugs = []
        tool.save()

        growth, _ = ToolGrowthMeta.objects.update_or_create(
            tool=tool,
            defaults={
                "is_viral": bool(spec.is_viral),
                "share_text": spec.share_text or {},
                "og_template": "viral" if spec.is_viral else "",
                "share_platforms": ["twitter", "linkedin", "copy"] if spec.is_viral else [],
            },
        )
        _append_log(job, f"growth_meta id={growth.pk} viral={growth.is_viral}")

        content_id = _maybe_create_howto_content(spec, tool, user=user)
        if content_id:
            _append_log(job, f"howto content_id={content_id}")

        test_path = _write_pytest_stub(spec.slug)
        artifacts: dict[str, Any] = {
            "tool_id": tool.tool_id,
            "definition_id": definition.pk,
            "test_stub": str(test_path),
            "content_id": content_id,
        }

        if spec.export_filesystem:
            paths = _export_filesystem(spec)
            artifacts["filesystem"] = paths
            _append_log(job, "filesystem scaffold written")

        invalidate_tool_caches(tool.slug)

        final_status = ToolSpec.Status.READY
        spec.status = final_status
        spec.error = ""
        spec.save(update_fields=["status", "error", "updated_at"])

        job.status = ToolFactoryJob.Status.SUCCESS
        job.artifacts = artifacts
        job.log = list(job.log or []) + ["build complete"]
        job.save(update_fields=["status", "artifacts", "log"])

        return {
            "spec_id": spec.pk,
            "slug": spec.slug,
            "status": spec.status,
            "tool_id": tool.tool_id,
            "job_id": job.pk,
            "artifacts": artifacts,
        }
    except Exception as exc:  # noqa: BLE001
        logger.exception("build_tool_from_spec failed for %s", spec_id)
        spec.status = ToolSpec.Status.FAILED
        spec.error = str(exc)[:4000]
        spec.save(update_fields=["status", "error", "updated_at"])
        job.status = ToolFactoryJob.Status.FAILED
        job.log = list(job.log or []) + [f"error: {exc}"]
        job.save(update_fields=["status", "log"])
        raise
