# Generated by Django 6.0.7 on 2026-07-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_launch_scale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflow',
            new_name='workflows_w_visibil_6307e3_idx',
            old_name='workflows_w_vis_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='workflows_w_workflo_b50f62_idx',
            old_name='workflows_w_wf_created_idx',
        ),
    ]
