# Generated by Django 6.0.7 on 2026-07-18 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools_registry', '0002_tool_faq_tool_howto_steps_tool_related_slugs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0)),
                ('tool_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_as_a', to='tools_registry.tool')),
                ('tool_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_as_b', to='tools_registry.tool')),
            ],
            options={
                'verbose_name_plural': 'tool affinities',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['tool_a', '-score'], name='recommendat_tool_a__6b3c59_idx'), models.Index(fields=['tool_b', '-score'], name='recommendat_tool_b__6a5e22_idx')],
                'unique_together': {('tool_a', 'tool_b')},
            },
        ),
    ]
