# Generated by Django 6.0.7 on 2026-07-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('tools_registry', '0002_tool_faq_tool_howto_steps_tool_related_slugs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('source_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_out', to='tools_registry.tool')),
                ('target_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_in', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['-relationship_score'],
                'indexes': [models.Index(fields=['source_tool', '-relationship_score'], name='recommendat_source__ae3d22_idx')],
                'unique_together': {('source_tool', 'target_tool')},
            },
        ),
    ]
