# Generated by Django 6.0.7 on 2026-07-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_hub', '0001_launch_scale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creatorsubmission',
            new_name='creator_hub_status_4b5730_idx',
            old_name='creator_hub_status_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorsubmission',
            new_name='creator_hub_type_4b3045_idx',
            old_name='creator_hub_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorusagestat',
            new_name='creator_hub_tool_sl_263fa6_idx',
            old_name='creator_hub_slug_period_idx',
        ),
    ]
