# Generated by Django 6.0.7 on 2026-07-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(default='run', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='tools_registry.tool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
