# Generated by Django 6.0.7 on 2026-07-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='toolhistory',
            index=models.Index(fields=['user', '-created_at'], name='history_too_user_id_ed76cd_idx'),
        ),
    ]
