# Generated by Django 6.0.7 on 2026-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ads_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='api_monthly_quota',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='plan',
            name='history_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_tool_runs',
            field=models.IntegerField(default=50, help_text='Monthly tool runs; -1 means unlimited'),
        ),
    ]
