# Generated by Django 6.0.7 on 2026-07-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSCProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_url', models.URLField(max_length=512, unique=True)),
                ('credentials_ref', models.CharField(blank=True, default='', help_text='Env key or file path reference for service-account credentials', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'GSC property',
                'verbose_name_plural': 'GSC properties',
                'ordering': ['site_url'],
            },
        ),
        migrations.CreateModel(
            name='GSCMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page', models.CharField(blank=True, db_index=True, default='', max_length=1024)),
                ('query', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('device', models.CharField(blank=True, default='', max_length=32)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='search_console.gscproperty')),
            ],
            options={
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['date', 'page'], name='search_cons_date_2e1fdc_idx'), models.Index(fields=['date', 'query'], name='search_cons_date_5cfe11_idx')],
            },
        ),
    ]
