# Generated by Django 6.0.7 on 2026-07-18 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, max_length=512)),
                ('locale', models.CharField(db_index=True, default='en', max_length=10)),
                ('search_volume', models.PositiveIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ranking_position', models.FloatField(blank=True, null=True)),
                ('ctr', models.FloatField(default=0.0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('suggested_tool_slug', models.SlugField(blank=True, default='', max_length=128)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Keyword opportunity',
                'verbose_name_plural': 'Keyword opportunities',
                'ordering': ['-priority_score', '-impressions'],
                'indexes': [models.Index(fields=['-priority_score'], name='keywords_ke_priorit_55a71f_idx'), models.Index(fields=['locale', '-search_volume'], name='keywords_ke_locale_ff570f_idx')],
                'unique_together': {('keyword', 'locale')},
            },
        ),
    ]
